name: adhd_0_1
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  simple_gradient_text: ^1.3.0
  device_preview: ^1.2.0
  connectivity_plus: ^6.0.5
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  cloud_firestore: ^5.6.11
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  share_plus: ^11.0.0
  url_launcher: ^6.1.7
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  flutter_timezone: ^4.1.0
  http: ^0.13.6
  gap: ^3.0.1
  awesome_notifications: ^0.10.1
  file_picker: ^8.1.2
  path_provider: ^2.1.5

flutter_native_splash:
  android_12:
    image: "assets/img/icons/brand_icon_a12.png"
  icon_background_color: "#000000"
  android: true
  ios: true
  web: false
  color: "#000000"
  image: "assets/img/icons/brand_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icons/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/img/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/sidebar/
    - assets/img/app_bg/png/
    - assets/img/buttons/
    - assets/img/prizes/
    - assets/img/icons/
    - assets/img/weather/
    - black_speech.env
    - assets/sound/lizard.wav

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
    - family: InterBlack
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Black.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf
    - family: Marvel
      fonts:
        - asset: assets/fonts/Marvel/Marvel-Regular.ttf
